services:
  mystreamhistoryweb:
    container_name: mystreamhistorywebcontainer
    image: ${TWC_REGISTRY_HOST}/mystreamhistoryweb:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt/live/mystreamhistory.com:/etc/letsencrypt/live/mystreamhistory.com:ro
      - /etc/letsencrypt/archive/mystreamhistory.com:/etc/letsencrypt/archive/mystreamhistory.com:ro
      - /etc/letsencrypt/renewal/mystreamhistory.com.conf:/etc/letsencrypt/renewal/mystreamhistory.com.conf:ro
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
